// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qibpmaoqrntwkvelmktp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpYnBtYW9xcm50d2t2ZWxta3RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1MDQyNTEsImV4cCI6MjA4NDA4MDI1MX0.zJafbtph_6dVAC983-VsrzSDAjfe89D5wQZSCqtc4Ag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});